name: Deploy to Proxmox
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PROXMOX_SSH_KEY }}" > ~/.ssh/proxmox_key
        chmod 600 ~/.ssh/proxmox_key
        ssh-keyscan -H 136.243.155.166 >> ~/.ssh/known_hosts

    - name: Deploy to Proxmox
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/proxmox_key -o StrictHostKeyChecking=no" \
          ./ root@136.243.155.166:/var/www/html/portfolio/

    - name: Verify deployment
      run: |
        sleep 5
        if curl -s --max-time 10 http://136.243.155.166:8082/ > /dev/null; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment verification failed"
          exit 1
        fi
